import Head from "next/head";
// import NavbarHome from "./NavbarHome";


export default function layout({ children }) {
  return (
    <>
      <Head>
        <title>BudgetExcursion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
}
